#!/usr/bin/env python3
# -*- mode: python; -*-

import argparse
import os
import sys
import subprocess

from lexer import lex
from parser import parse
from annotator import annotate
from backend import generate_code

if __name__ == "__main__":
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument('source_name', help="file to compile")
    arg_parser.add_argument('--just-rust', action='store_true',
                            help="print generated Rust, but don't compile")
    args = arg_parser.parse_args()

    source_name = args.source_name
    if not source_name.endswith(".gltrl"):
        print("Glitteral source files must have the .gltrl extension.")
        sys.exit(1)
    output_name = source_name[:-6]  # less ".gltrl"
    with open(sys.argv[1]) as source_file:
        source = source_file.read()

    generated_code = generate_code(annotate(parse(lex(source))))
    if args.just_rust:
        print(generated_code)
        sys.exit(0)

    ir_name = "__{}_compiled.rs".format(source_name)
    with open(ir_name, 'w') as code_file:
        code_file.write(generated_code)
    exit_code = subprocess.call(
        ['rustc',
         '--allow', "dead_code",
         '--allow', "non_snake_case",
         '--allow', "unused_variables",
         '--allow', "unused_mut",
         '--crate-name', output_name,
         ir_name]
    )
    sys.exit(exit_code)
