#!/usr/bin/env python3

import os
import sys
import subprocess

from lexer import lex
from parser import parse
from backend import generate_code

if __name__ == "__main__":
    source_name = sys.argv[1]
    output_name = source_name[:-6]  # less ".gltrl"
    with open(sys.argv[1]) as source_file:
        source = source_file.read()
    with open("__glitteral_compiled.rs", 'w') as code_file:
        code_file.write(generate_code(parse(lex(source))))
    subprocess.check_call(['rustc', '__glitteral_compiled.rs',
                           '--crate-name', output_name])
